export default {
  APP_CHANGE_LOCALE: 'APP_CHANGE_LOCALE',
  APP_CHANGE_MAIN_MENU_STATE: 'APP_CHANGE_MAIN_MENU_STATE',
  DASHBOARD_ADD_WIDGET: 'DASHBOARD_ADD_WIDGET',
  DASHBOARD_CHANGE_LAYOUTS: 'DASHBOARD_CHANGE_LAYOUTS',
  DASHBOARD_CHANGE_CURRENT_BREAKPOINT: 'DASHBOARD_CHANGE_CURRENT_BREAKPOINT',
};
